### ISSUE TITLE
correct running steps

### ISSUE THREAD

**Issue by Damcy** [SivilTaram/dialogue-utterance-rewriter-py3#2]
Thanks for your great job!
I can run the `train.sh` script and get models in `./log/extractive/train`.

Then I change `coverage=1` and `convert_to_coverage_model=1` to get the coverage model. After running the `new train.sh` script, I get `./log/extractive/train/model.ckpt-xxx_cov_init*` files.

Then I run the `test.sh / val.sh`, but they can not work properly. They search the model in different paths. But when I place those coverage model files in the corresponding path, it raises another error.
`tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [4004,128] rhs shape= [4000,128]`
`Errors may have originated from an input operation.`
`Input Source operations connected to node save/Assign_17:
 seq2seq/embedding/embedding (defined at /home/stmayue/query_rewrite/github/dialogue-utterance-rewriter-py3/model.py:362)`

**Comment by SivilTaram** [comment]
@Damcy Do you modify `convert_to_coverage_model=1` in `val.sh` ?

**Comment by Damcy** [comment]
@SivilTaram 不是的。我发现和coverage无关。
启动train.sh然后再启动val.sh，也会报shape不匹配。train是没问题的，但是val脚本就会一直加载不上模型，在load_ckp那里一直循环，实际错误是上面贴出来的shape不匹配。

**Comment by Damcy** [comment]
词表的shape一个是4000\*128，一个是4004\*128

**Comment by SivilTaram** [comment]
Is it nomral when you use the original `train.sh` and `val.sh`? 4004 is the vocabulary size. I don't know why it could be an issue :(.

It works fine on my machine using the original train.sh and val.sh.

**Comment by Damcy** [comment]
I only change the CUDA setting in train.sh and val.sh.

**Comment by Damcy** [comment]
I find that the vocab size in train.sh is 4000, but the vocab size in val.sh is 4004.

I add `tf.logging.info("size of vocab: %d" % vocab.size())` in model.py line 24.

**Comment by SivilTaram** [comment]
@Damcy Thanks. It reminds me to check and now it has been fixed. Please pull the latest changes and run again.

**Comment by Damcy** [comment]
Yes. Change the vocab_size to 4004 in the train.sh may work.

**Comment by LLLLLLoki** [comment]
这个模型的epoch 是多少啊  我没找到

**Comment by SivilTaram** [comment]
@LLLLLLoki It will run all the time until it is shutdown.

**Comment by LLLLLLoki** [comment]
我在sh test.sh 的时候也发生了这个错误，这个怎么修改的啊？

tensors to match. lhs shape= [4004,128] rhs shape= [4000,128]
         [[{{node save/Assign_17}}]]
好像是训练的时候少了这四个[MARK_UNK, MARK_PAD, MARK_GO, MARK_EOS] 字表

**Comment by SivilTaram** [comment]
@LLLLLLoki I have fixed the same problem in `test.sh`. You could expect it to be correct now.
